### ISSUE TITLE
在代码中填入API key

### ISSUE THREAD

**Issue by 827648313** [xinsblog/try-llama-index#1]
在代码中填入API key， 指的是哪里的代码呢

**Comment by xinsblog** [comment]
我的这个demo版本算比较老的了，你可以参考下最新版的llama-index库的文档，里面应该会有介绍，或者可以求助大模型解决这个问题：

<img width="812" alt="image" src="https://github.com/xinsblog/try-llama-index/assets/1934999/140a561b-4d2c-4363-b5ab-e53f71c1982c">
